### ISSUE TITLE
Spruce Slab Vertical Placement Crash

### ISSUE THREAD

**Issue by JAMalcolmson** [FirEmerald/AdditionalPlacements#19]
Crashed when trying to place spruce slab vertically against near-edge of vertically oriented spruce log block, above my head, while another spruce slab was partially obstructing my view.

I understand I have 250 mods running simultaneously, but none of them are adding unique blocks, this interaction was with vanilla objects.

![crash moment](https://user-images.githubusercontent.com/88909897/204765451-c87e9859-d82d-4f03-9a10-084d38d4113e.jpg)

[latest.log](https://github.com/FirEmerald/AdditionalPlacements/files/10121872/latest.log)

[crash-2022-11-30_02.47.18-client.txt](https://github.com/FirEmerald/AdditionalPlacements/files/10121879/crash-2022-11-30_02.47.18-client.txt)

**Comment by FirEmerald** [comment]
fixed by
https://github.com/FirEmerald/AdditionalPlacements/commit/b7fbfdc39a26c55d0e5e4bdd197f2a09dc6f1961 (1.16.5)
https://github.com/FirEmerald/AdditionalPlacements/commit/f531cd2f78f8e15b119f27967aca0c24e75abae2 (1.18.2)
https://github.com/FirEmerald/AdditionalPlacements/commit/0f93f9374b42de5146a5db8a008629a705e2b28c (1.19.2)
