### ISSUE TITLE
Visual error.

### ISSUE THREAD

**Issue by bastegk2** [FirEmerald/AdditionalPlacements#28]
I use your mod for my Modpack VR MRWS. I use physics mod and a Custom texturepack with new path systm for blocks, the placement works well. But the "Particle" has no texture get a white style with letter T.

**Comment by FirEmerald** [comment]
It would help if you could share a list of the mods being used and some screenshots of the issue in question

**Comment by bastegk2** [comment]
I think it is the  physics mod with the custom ressource pack i test it out and let you know if this is this mod.   [https://cdn.discordapp.com/attachments/1093974910164017274/1112731859353342092/2023-05-29_15.14.42.png](url)

**Comment by FirEmerald** [comment]
What's odd here is it seems like the built-in "resourcepack" that provides generated models isn't being used at all, which would most likely mean for some reason the "AddPackFindersEvent" isn't being fired.

**Comment by FirEmerald** [comment]
Should hopefully be fixed by
https://github.com/FirEmerald/AdditionalPlacements/commit/183ac9fb9871ab6fb92e45afee3044f8d663f06d
https://github.com/FirEmerald/AdditionalPlacements/commit/ad39799431dd5c0439294d5989a68b669c05a438
https://github.com/FirEmerald/AdditionalPlacements/commit/1ba229add23761004db795cd27be69f298ef9bc1
https://github.com/FirEmerald/AdditionalPlacements/commit/b6615b5a0f3fb313c117f22620a6abd78a427030
