### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [FirEmerald/AdditionalPlacements#32]
```
Minecraft v1.19.2
Additional Placements v1.7.1
```

The server crashes with the new update, the previous version 1.7.0 doesn't crash. 
[Server Log](https://gist.github.com/WenXin20/ecd7aae9b861e2c41d5901c5f950730a#file-server_latest-log-L1147)

**Comment by FirEmerald** [comment]
Fixed by
https://github.com/FirEmerald/AdditionalPlacements/commit/cd60b7a2b1fe697dc167a342d6ac25433dd39765 (1.16.5)
https://github.com/FirEmerald/AdditionalPlacements/commit/1a51e209c7ce67b3279e6d99b9a4e8bc212e8557 (1.18.2)
https://github.com/FirEmerald/AdditionalPlacements/commit/eb2649f3cb5a51db391850009ef68e493de89813 (1.19.2)
