### ISSUE TITLE
Missing Texture For Breaking Particles

### ISSUE THREAD

**Issue by peepeepoopoocaca** [FirEmerald/AdditionalPlacements#45]
While using this mod with the Physics Mod, breaking vertical slabs and vertical stairs causes the breaking particles to show a missing texture. This is on the newest available version for 1.20.1.

**Comment by FirEmerald** [comment]
Most likely, the Physics Mod is causing the game to incorrectly call `getParticleIcon()` as opposed to `getParticleIcon(ModelData)`

**Comment by FirEmerald** [comment]
Should hopefully be fixed by
https://github.com/FirEmerald/AdditionalPlacements/commit/183ac9fb9871ab6fb92e45afee3044f8d663f06d
https://github.com/FirEmerald/AdditionalPlacements/commit/ad39799431dd5c0439294d5989a68b669c05a438
https://github.com/FirEmerald/AdditionalPlacements/commit/1ba229add23761004db795cd27be69f298ef9bc1
https://github.com/FirEmerald/AdditionalPlacements/commit/b6615b5a0f3fb313c117f22620a6abd78a427030
